language: c++

compiler:
    - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libqd-dev
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y git
  - sudo apt-get install -y libboost-python-dev
  - sudo apt-get install -y libboost-program-options-dev
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake ../src

script: 
  - make
  - make test ARGS="-R cpp"

